// lib/data.js

export const COURSES = [
  {
    id: 'python',
    title: 'Python Mastery',
    icon: '🐍',
    accent: '#3b82f6',
    accentLight: '#eff6ff',
    accentDark: '#1e3a5f',
    tag: 'Beginner → Advanced',
    duration: '42 hrs',
    lessons: 8,
    students: 18240,
    rating: 4.9,
    reviews: 2140,
    description: 'From syntax basics to OOP, NumPy, Pandas and real-world automation - a complete Python journey.',
    skills: ['Variables & Types', 'OOP', 'NumPy', 'Pandas', 'File I/O', 'APIs'],
    videos: [
      { title: 'Introduction to Python', duration: '12:30', preview: true },
      { title: 'Variables & Data Types', duration: '18:45', preview: false },
      { title: 'Control Flow & Loops', duration: '22:10', preview: false },
      { title: 'Functions & Modules', duration: '25:00', preview: false },
      { title: 'Object Oriented Programming', duration: '35:20', preview: false },
      { title: 'File Handling & Exceptions', duration: '20:15', preview: false },
      { title: 'NumPy & Pandas Deep Dive', duration: '40:00', preview: false },
      { title: 'Capstone Project', duration: '30:00', preview: false },
    ],
  },
  {
    id: 'java',
    title: 'Java Development',
    icon: '☕',
    accent: '#f59e0b',
    accentLight: '#fffbeb',
    accentDark: '#713f12',
    tag: 'Beginner → Advanced',
    duration: '38 hrs',
    lessons: 6,
    students: 12580,
    rating: 4.8,
    reviews: 1320,
    description: 'Core Java, OOP patterns, Collections, multithreading and enterprise Spring Boot applications.',
    skills: ['OOP', 'Collections', 'Streams', 'Spring Boot', 'REST APIs', 'JUnit'],
    videos: [
      { title: 'Java Environment & Basics', duration: '10:00', preview: true },
      { title: 'OOP in Java', duration: '28:00', preview: false },
      { title: 'Collections & Generics', duration: '22:30', preview: false },
      { title: 'Exception Handling', duration: '18:00', preview: false },
      { title: 'Multithreading & Concurrency', duration: '32:00', preview: false },
      { title: 'Spring Boot Fundamentals', duration: '38:00', preview: false },
    ],
  },
  {
    id: 'fullstack',
    title: 'Full Stack Web Dev',
    icon: '🌐',
    accent: '#8b5cf6',
    accentLight: '#f5f3ff',
    accentDark: '#3b0764',
    tag: 'Intermediate',
    duration: '56 hrs',
    lessons: 7,
    students: 22100,
    rating: 4.9,
    reviews: 2870,
    description: 'HTML, CSS, JavaScript, Node.js, SQL and NoSQL databases - build and deploy complete web apps.',
    skills: ['HTML5/CSS3', 'JavaScript', 'Node.js', 'Express', 'PostgreSQL', 'Docker'],
    videos: [
      { title: 'HTML5 & CSS3 Foundations', duration: '25:00', preview: true },
      { title: 'Responsive Design & Flexbox', duration: '20:00', preview: false },
      { title: 'JavaScript Deep Dive', duration: '45:00', preview: false },
      { title: 'Node.js & Express APIs', duration: '35:00', preview: false },
      { title: 'SQL & NoSQL Databases', duration: '30:00', preview: false },
      { title: 'Authentication & Security', duration: '28:00', preview: false },
      { title: 'Deployment & CI/CD', duration: '25:00', preview: false },
    ],
  },
  {
    id: 'mern',
    title: 'MERN Stack',
    icon: '⚛️',
    accent: '#10b981',
    accentLight: '#ecfdf5',
    accentDark: '#064e3b',
    tag: 'Intermediate',
    duration: '48 hrs',
    lessons: 7,
    students: 15300,
    rating: 4.8,
    reviews: 1760,
    description: 'MongoDB, Express, React and Node - architect, build and deploy production full-stack apps.',
    skills: ['MongoDB', 'Express', 'React', 'Node.js', 'Redux', 'JWT Auth'],
    videos: [
      { title: 'MongoDB & Mongoose ODM', duration: '30:00', preview: true },
      { title: 'Express REST API Design', duration: '28:00', preview: false },
      { title: 'React Fundamentals', duration: '40:00', preview: false },
      { title: 'React Hooks & Context', duration: '35:00', preview: false },
      { title: 'Redux Toolkit', duration: '30:00', preview: false },
      { title: 'JWT Auth End-to-End', duration: '32:00', preview: false },
      { title: 'Production Deployment', duration: '22:00', preview: false },
    ],
  },
  {
    id: 'datascience',
    title: 'Data Science',
    icon: '📊',
    accent: '#ec4899',
    accentLight: '#fdf2f8',
    accentDark: '#500724',
    tag: 'Intermediate',
    duration: '52 hrs',
    lessons: 7,
    students: 19800,
    rating: 4.9,
    reviews: 2430,
    description: 'Statistics, EDA, Matplotlib, Seaborn, Scikit-learn - tell compelling stories with data.',
    skills: ['Statistics', 'Pandas', 'Matplotlib', 'Seaborn', 'Scikit-learn', 'Tableau'],
    videos: [
      { title: 'Statistics & Probability', duration: '35:00', preview: true },
      { title: 'Data Wrangling with Pandas', duration: '30:00', preview: false },
      { title: 'Matplotlib & Seaborn', duration: '25:00', preview: false },
      { title: 'Exploratory Data Analysis', duration: '28:00', preview: false },
      { title: 'Machine Learning Intro', duration: '40:00', preview: false },
      { title: 'Model Evaluation & Metrics', duration: '22:00', preview: false },
      { title: 'Capstone: Real Dataset', duration: '35:00', preview: false },
    ],
  },
  {
    id: 'ml',
    title: 'ML Engineering',
    icon: '🤖',
    accent: '#f97316',
    accentLight: '#fff7ed',
    accentDark: '#431407',
    tag: 'Advanced',
    duration: '60 hrs',
    lessons: 6,
    students: 9450,
    rating: 4.8,
    reviews: 980,
    description: 'Supervised, unsupervised & reinforcement learning pipelines. MLOps, model serving at scale.',
    skills: ['Scikit-learn', 'XGBoost', 'MLflow', 'Feature Eng', 'Docker', 'FastAPI'],
    videos: [
      { title: 'ML Fundamentals & Math', duration: '35:00', preview: true },
      { title: 'Supervised Learning Algorithms', duration: '40:00', preview: false },
      { title: 'Unsupervised & Clustering', duration: '32:00', preview: false },
      { title: 'Feature Engineering', duration: '28:00', preview: false },
      { title: 'Model Selection & Tuning', duration: '30:00', preview: false },
      { title: 'MLOps & Model Serving', duration: '38:00', preview: false },
    ],
  },
  {
    id: 'deeplearning',
    title: 'Deep Learning',
    icon: '🧠',
    accent: '#6366f1',
    accentLight: '#eef2ff',
    accentDark: '#1e1b4b',
    tag: 'Advanced',
    duration: '65 hrs',
    lessons: 7,
    students: 7200,
    rating: 4.9,
    reviews: 840,
    description: 'Neural networks, CNNs, RNNs, Transformers, fine-tuning LLMs and edge AI deployment.',
    skills: ['PyTorch', 'CNNs', 'RNNs', 'Transformers', 'HuggingFace', 'ONNX'],
    videos: [
      { title: 'Neural Network Foundations', duration: '38:00', preview: true },
      { title: 'Backpropagation & Optimizers', duration: '35:00', preview: false },
      { title: 'CNNs for Computer Vision', duration: '42:00', preview: false },
      { title: 'RNNs, LSTMs & Sequences', duration: '38:00', preview: false },
      { title: 'Transformers & Attention', duration: '45:00', preview: false },
      { title: 'Fine-tuning LLMs', duration: '40:00', preview: false },
      { title: 'Edge AI & Deployment', duration: '30:00', preview: false },
    ],
  },
]

export const TESTIMONIALS = [
  { name: 'Aryan Sharma', role: 'ML Engineer @ Google', avatar: 'A', course: 'Deep Learning', text: 'ElevateU got me into my dream role. The structured video lessons and real projects made all the difference.' },
  { name: 'Priya Mehta', role: 'Full Stack Dev @ Razorpay', avatar: 'P', course: 'MERN Stack', text: 'The MERN track is hands-down the best I\'ve found. Built 3 production apps by the end.' },
  { name: 'Rahul Gupta', role: 'Data Scientist @ Flipkart', avatar: 'R', course: 'Data Science', text: 'Certificate helped me switch careers in 6 months. The EDA and ML content is genuinely industry-grade.' },
]

export const FAQS = [
  { q: 'Are the certificates recognised by employers?', a: 'Yes - ElevateU certificates are recognised by 500+ hiring partners across India and globally, including Flipkart, Razorpay, Infosys, and Wipro.' },
  { q: 'Can I learn at my own pace?', a: 'Absolutely. All lessons are on-demand. Once enrolled you have lifetime access and can watch anytime, anywhere.' },
  { q: 'What if I get stuck on a topic?', a: 'Each course has a community Q&A section where mentors respond within 24 hours. You can also revisit any lesson as many times as needed.' },
  { q: 'Is there a refund policy?', a: 'We offer a 7-day no-questions-asked refund on all courses. If you are not satisfied, we will process it instantly.' },
]

export function formatStudents(n) {
  if (n >= 1000) return (n / 1000).toFixed(1) + 'k'
  return n.toString()
}

export function generateCertId() {
  return 'EU-' + Math.random().toString(36).substr(2, 8).toUpperCase()
}
